from core.shared.exceptions import AlreadyExistsException


class UserAlreadyExistsException(AlreadyExistsException):
    pass
