from core.shared.exceptions import NotFoundException


class UserNotFoundException(NotFoundException):
    pass
