from core.shared.exceptions import AlreadyExistsException


class CategoryAlreadyExistException(AlreadyExistsException):
    pass
